\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={HW\#6},
            pdfauthor={Haichuan Du},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\providecommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{HW\#6}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Haichuan Du}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{7/8/2020}


\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{setwd}\NormalTok{(}\StringTok{"~/Desktop/statistics/Nonparametric/project"}\NormalTok{)}
\NormalTok{churn_data <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"churn.csv"}\NormalTok{)}
\KeywordTok{head}\NormalTok{(churn_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   customerID gender SeniorCitizen Partner Dependents tenure PhoneService
## 1 7590-VHVEG Female             0     Yes         No      1           No
## 2 5575-GNVDE   Male             0      No         No     34          Yes
## 3 3668-QPYBK   Male             0      No         No      2          Yes
## 4 7795-CFOCW   Male             0      No         No     45           No
## 5 9237-HQITU Female             0      No         No      2          Yes
## 6 9305-CDSKC Female             0      No         No      8          Yes
##      MultipleLines InternetService OnlineSecurity OnlineBackup
## 1 No phone service             DSL             No          Yes
## 2               No             DSL            Yes           No
## 3               No             DSL            Yes          Yes
## 4 No phone service             DSL            Yes           No
## 5               No     Fiber optic             No           No
## 6              Yes     Fiber optic             No           No
##   DeviceProtection TechSupport StreamingTV StreamingMovies       Contract
## 1               No          No          No              No Month-to-month
## 2              Yes          No          No              No       One year
## 3               No          No          No              No Month-to-month
## 4              Yes         Yes          No              No       One year
## 5               No          No          No              No Month-to-month
## 6              Yes          No         Yes             Yes Month-to-month
##   PaperlessBilling             PaymentMethod MonthlyCharges TotalCharges
## 1              Yes          Electronic check          29.85        29.85
## 2               No              Mailed check          56.95      1889.50
## 3              Yes              Mailed check          53.85       108.15
## 4               No Bank transfer (automatic)          42.30      1840.75
## 5              Yes          Electronic check          70.70       151.65
## 6              Yes          Electronic check          99.65       820.50
##   Churn
## 1    No
## 2    No
## 3   Yes
## 4    No
## 5   Yes
## 6   Yes
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{attach}\NormalTok{(churn_data)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{0}\NormalTok{)}
\NormalTok{samp <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{7}\NormalTok{, }\DecValTok{10}\NormalTok{, }\DecValTok{10}\NormalTok{, }\DecValTok{10}\NormalTok{, }\DecValTok{11}\NormalTok{, }\DecValTok{12}\NormalTok{, }\DecValTok{12}\NormalTok{, }\DecValTok{13}\NormalTok{, }\DecValTok{13}\NormalTok{, }\DecValTok{14}\NormalTok{, }\DecValTok{14}\NormalTok{, }\DecValTok{15}\NormalTok{, }\DecValTok{22}\NormalTok{, }\DecValTok{31}\NormalTok{, }\DecValTok{37}\NormalTok{)}
\NormalTok{n=}\KeywordTok{length}\NormalTok{(samp)}
\NormalTok{B=}\DecValTok{1000} \CommentTok{#Number of bootstrap samples to draw.}
\NormalTok{sdvec=}\KeywordTok{double}\NormalTok{(B) }\CommentTok{#Saving the bootstrap standard deviations.}
\NormalTok{meavec=}\KeywordTok{double}\NormalTok{(B) }\CommentTok{#Saving the bootstrap sample means.}
\NormalTok{coevar=}\KeywordTok{double}\NormalTok{(B)}
\NormalTok{sd=}\KeywordTok{sd}\NormalTok{(samp) }\CommentTok{#Observed standard deviation.}
\NormalTok{mea=}\KeywordTok{mean}\NormalTok{(samp) }\CommentTok{#Observed sample mean.}
\NormalTok{cov=}\KeywordTok{sd}\NormalTok{(samp)}\OperatorTok{/}\KeywordTok{mean}\NormalTok{(samp)}
\ControlFlowTok{for}\NormalTok{ (brun }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\NormalTok{B)\{}
\NormalTok{  bsamp=}\KeywordTok{sample}\NormalTok{(samp,n,}\DataTypeTok{replace=}\NormalTok{T) }\CommentTok{#Sample with replacement from the sample., 从sample里面取10次}
\NormalTok{  meavec[brun]=}\KeywordTok{mean}\NormalTok{(bsamp)}
\NormalTok{  sdvec[brun]=}\KeywordTok{sd}\NormalTok{(bsamp)}
\NormalTok{  coevar[brun]=}\KeywordTok{sd}\NormalTok{(bsamp)}\OperatorTok{/}\KeywordTok{mean}\NormalTok{(bsamp)\}}
\KeywordTok{hist}\NormalTok{(meavec) }\CommentTok{#Plotting the bootstrap means.}
\KeywordTok{abline}\NormalTok{(}\DataTypeTok{v=}\NormalTok{mea)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-2-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{hist}\NormalTok{(sdvec) }\CommentTok{#Plotting the bootstrap standard deviations.}
\KeywordTok{abline}\NormalTok{(}\DataTypeTok{v=}\NormalTok{sd)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-2-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Now studying the mean.}

\NormalTok{ehat=}\KeywordTok{mean}\NormalTok{(meavec) }\CommentTok{#Mean of the bootstrap values. -------point estimate}
\NormalTok{msehat=}\KeywordTok{mean}\NormalTok{((meavec}\OperatorTok{-}\NormalTok{mea)}\OperatorTok{^}\DecValTok{2}\NormalTok{) }\CommentTok{#Estimated MSE.}
\NormalTok{se=}\KeywordTok{sqrt}\NormalTok{(msehat) }\CommentTok{#Bootstrap SE---------> standard error.}
\NormalTok{bhat=ehat}\OperatorTok{-}\NormalTok{mea }\CommentTok{#Estimated ----------> bootstrap bias.}
\NormalTok{CI=}\KeywordTok{quantile}\NormalTok{(meavec,}\KeywordTok{c}\NormalTok{(}\FloatTok{0.025}\NormalTok{,}\FloatTok{0.975}\NormalTok{))}
\NormalTok{ehat}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 15.39653
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{msehat}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4.140818
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{se}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.0349
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{bhat}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -0.003466667
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{CI}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     2.5%    97.5% 
## 11.73333 19.80167
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Now studying the standard deviation.}

\NormalTok{ehat=}\KeywordTok{mean}\NormalTok{(sdvec) }\CommentTok{#standard deviation. of the bootstrap values.----> point estimate}
\NormalTok{msehat=}\KeywordTok{mean}\NormalTok{((sdvec}\OperatorTok{-}\NormalTok{sd)}\OperatorTok{^}\DecValTok{2}\NormalTok{) }\CommentTok{#Estimated MSE.}
\NormalTok{se=}\KeywordTok{sqrt}\NormalTok{(msehat) }\CommentTok{#Bootstrap SE.}
\NormalTok{bhat=ehat}\OperatorTok{-}\NormalTok{sd }\CommentTok{#Estimated bias.}
\NormalTok{CI=}\KeywordTok{quantile}\NormalTok{(sdvec,}\KeywordTok{c}\NormalTok{(}\FloatTok{0.025}\NormalTok{,}\FloatTok{0.975}\NormalTok{))}
\NormalTok{ehat}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 7.659678
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{msehat}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5.348207
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{se}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.312619
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{bhat}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -0.6624092
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{CI}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      2.5%     97.5% 
##  2.260737 11.342461
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Now studying the  population coefficient of variation.}

\NormalTok{ehat=}\KeywordTok{mean}\NormalTok{(coevar) }\CommentTok{#coefficient of variation of the bootstrap values.----> point estimate}
\NormalTok{msehat=}\KeywordTok{mean}\NormalTok{((coevar}\OperatorTok{-}\NormalTok{cov)}\OperatorTok{^}\DecValTok{2}\NormalTok{) }\CommentTok{#Estimated MSE.}
\NormalTok{se=}\KeywordTok{sqrt}\NormalTok{(msehat) }\CommentTok{#Bootstrap SE.}
\NormalTok{bhat=ehat}\OperatorTok{-}\NormalTok{cov }\CommentTok{#Estimated bias.}
\NormalTok{CI=}\KeywordTok{quantile}\NormalTok{(coevar,}\KeywordTok{c}\NormalTok{(}\FloatTok{0.025}\NormalTok{,}\FloatTok{0.975}\NormalTok{))}
\NormalTok{ehat}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.4897533
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{msehat}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.01428481
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{se}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1195191
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{bhat}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -0.050642
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{CI}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      2.5%     97.5% 
## 0.2021840 0.6418488
\end{verbatim}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\item
  For the population mean point estimates = 15.39653 bootstrap standard
  errors = 2.0349 bootstrap bias estimates = -0.003466667 95\% bootstrap
  percentile confidence intervals = (11.73333, 19.80167 )
\item
  For the population standard deviation point estimates = 7.659678
  bootstrap standard errors = 2.312619 bootstrap bias estimates =
  -0.6624092 95\% bootstrap percentile confidence intervals = (2.260737,
  11.342461)
\item
  For the population coefficient of variation point estimates =
  0.4897533 bootstrap standard errors = 0.1195191 bootstrap bias
  estimates = -0.050642 95\% bootstrap percentile confidence intervals =
  (0.2021840, 0.6418488)
\end{enumerate}

The population standard deviation is seriously biased(bootstrap bias
estimates = -0.6624092)

\#3

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sample_size <-}\StringTok{ }\NormalTok{churn_data}\OperatorTok{$}\NormalTok{MonthlyCharges}
\KeywordTok{length}\NormalTok{(sample_size)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 7043
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size))}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# par(mfrow=c(2,2))}
\NormalTok{fit1=}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'gaussian'}\NormalTok{) }\CommentTok{#Using default bandwidth.}
\NormalTok{fit2=}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'epanechnikov'}\NormalTok{)}
\NormalTok{fit3=}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'rectangular'}\NormalTok{)}
\NormalTok{fit4=}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'biweight'}\NormalTok{)}
\KeywordTok{plot}\NormalTok{(fit1,}\DataTypeTok{main=}\StringTok{'Gaussian'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(fit2,}\DataTypeTok{main=}\StringTok{'Epanechnikov'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(fit3,}\DataTypeTok{main=}\StringTok{'Rectangular'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-4.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(fit4,}\DataTypeTok{main=}\StringTok{'Biweight'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-5.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Different bandwidths for gaussian kernal}
\CommentTok{# par(mfrow=c(4,4))}
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'gaussian'}\NormalTok{,}\DataTypeTok{bw=}\FloatTok{0.1}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-6.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'gaussian'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{1}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-7.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'gaussian'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{3}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-8.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'gaussian'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{5}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-9.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'gaussian'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{10}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-10.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'gaussian'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{20}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-11.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'gaussian'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{25}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-12.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'gaussian'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{30}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-13.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'gaussian'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{40}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-14.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'gaussian'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{50}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-15.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Different bandwidths for epanechnikov kernal}
\CommentTok{# par(mfrow=c(4,4))}
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'epanechnikov'}\NormalTok{,}\DataTypeTok{bw=}\FloatTok{0.1}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-16.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'epanechnikov'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{1}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-17.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'epanechnikov'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{3}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-18.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'epanechnikov'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{5}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-19.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'epanechnikov'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{10}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-20.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'epanechnikov'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{20}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-21.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'epanechnikov'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{25}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-22.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'epanechnikov'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{30}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-23.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'epanechnikov'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{40}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-24.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'epanechnikov'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{50}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-25.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Different bandwidths for rectangular kernal}
\CommentTok{# par(mfrow=c(4,4))}
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'rectangular'}\NormalTok{,}\DataTypeTok{bw=}\FloatTok{0.1}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-26.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'rectangular'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{1}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-27.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'rectangular'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{3}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-28.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'rectangular'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{5}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-29.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'rectangular'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{10}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-30.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'rectangular'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{20}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-31.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'rectangular'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{25}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-32.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'rectangular'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{30}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-33.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'rectangular'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{40}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-34.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'rectangular'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{50}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-35.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Different bandwidths for biweight kernal}
\CommentTok{# par(mfrow=c(4,4))}
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'biweight'}\NormalTok{,}\DataTypeTok{bw=}\FloatTok{0.1}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-36.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'biweight'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{1}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-37.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'biweight'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{3}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-38.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'biweight'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{5}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-39.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'biweight'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{10}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-40.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'biweight'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{20}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-41.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'biweight'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{25}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-42.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'biweight'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{30}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-43.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'biweight'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{40}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-44.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(sample_size,}\DataTypeTok{kernel=}\StringTok{'biweight'}\NormalTok{,}\DataTypeTok{bw=}\DecValTok{50}\NormalTok{),}\DataTypeTok{main=}\StringTok{''}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW-6_files/figure-latex/unnamed-chunk-3-45.pdf} (i) The
sample size: Sample size for MonthlyCharges is 7043 (ii) The kernel that
I used: Gaussian, Epanechnikov, Rectangular, Biweight (iii) The
bandwidth: The bandwidth I used incluing 0.1, 1, 3, 5, 10, 20, 25, 30,
40, 50

Comment on what the plot of the estimated density suggests about the
shape of the distribution. Please indicate which bandwidths you tried
(Do try some!) in addition to the default choice.

In general, with the constant increase of the bandwidth of the four
kernels, the shape of the density gradually presents unimodal shape,
approaching their original kernel function.

For gaussian kernel: When the bandwidth is less than 3, the density
shape appears jagged; when the bandwidth is greater than 3 and less than
10, the density shape changes from 3 humps to 2; when the bandwidth is
greater than 20, the density shape initially appears unimodal and tends
to the original kernel function

For epanechnikov kernel: similar to to gaussian kernel, when the
bandwidth \textless{}= 3, the density shape appears jagged; when the
bandwidth is greater than 3 and less than 10, the density shape changes
from 3 humps to 2 but has a smoother curve; when the bandwidth is
greater than 20, the density shape initially appears unimodal and tends
to the original kernel function。

For rectangular kernel: When the bandwidth is less than 10, the density
shape is jagged, when the bandwidth is greater than 3 and less than 20,
the hump gradually changes from 3 to 1 and the curve tends to be flat.
When the bandwidth is greater than 25, the top shape of the hump tends
to be close to the original kernel functio like straight line.

For biweight kernel: very similar to the gaussian kernel, gaussian
kernel is little bit smoother than biweight.


\end{document}
